In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from tqdm import tqdm
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
iris = load_iris()
data = np.hstack((iris['data'],[[f'Gerard {i + 1}'] for i in range(len(iris['data']))]))
y_true = iris['target']
data

array([['5.1', '3.5', '1.4', '0.2', 'Gerard 1'],
       ['4.9', '3.0', '1.4', '0.2', 'Gerard 2'],
       ['4.7', '3.2', '1.3', '0.2', 'Gerard 3'],
       ['4.6', '3.1', '1.5', '0.2', 'Gerard 4'],
       ['5.0', '3.6', '1.4', '0.2', 'Gerard 5'],
       ['5.4', '3.9', '1.7', '0.4', 'Gerard 6'],
       ['4.6', '3.4', '1.4', '0.3', 'Gerard 7'],
       ['5.0', '3.4', '1.5', '0.2', 'Gerard 8'],
       ['4.4', '2.9', '1.4', '0.2', 'Gerard 9'],
       ['4.9', '3.1', '1.5', '0.1', 'Gerard 10'],
       ['5.4', '3.7', '1.5', '0.2', 'Gerard 11'],
       ['4.8', '3.4', '1.6', '0.2', 'Gerard 12'],
       ['4.8', '3.0', '1.4', '0.1', 'Gerard 13'],
       ['4.3', '3.0', '1.1', '0.1', 'Gerard 14'],
       ['5.8', '4.0', '1.2', '0.2', 'Gerard 15'],
       ['5.7', '4.4', '1.5', '0.4', 'Gerard 16'],
       ['5.4', '3.9', '1.3', '0.4', 'Gerard 17'],
       ['5.1', '3.5', '1.4', '0.3', 'Gerard 18'],
       ['5.7', '3.8', '1.7', '0.3', 'Gerard 19'],
       ['5.1', '3.8', '1.5', '0.3', 'Gerard 20'],
       ['

In [3]:
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'], 
                     index=[f'Gerard {i + 1}' for i in range(len(data))])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Gerard 1                  5.1               3.5                1.4   
Gerard 2                  4.9               3.0                1.4   
Gerard 3                  4.7               3.2                1.3   
Gerard 4                  4.6               3.1                1.5   
Gerard 5                  5.0               3.6                1.4   
...                       ...               ...                ...   
Gerard 146                6.7               3.0                5.2   
Gerard 147                6.3               2.5                5.0   
Gerard 148                6.5               3.0                5.2   
Gerard 149                6.2               3.4                5.4   
Gerard 150                5.9               3.0                5.1   

            petal width (cm)  target  
Gerard 1                 0.2     0.0  
Gerard 2                 0.2     0.0  
Gerard 3                 0.2     0.0  
Gerard 4                 0.2     0.0  
Gerard 5                 0.2     0.0  
...                      ...     ...  
Gerard 146               2.3     2.0  
Gerard 147               1.9     2.0  
Gerard 148               2.0     2.0  
Gerard 149               2.3     2.0  
Gerard 150               1.8     2.0  

[150 rows x 5 columns]

In [4]:
columns_mins = df.min(axis=0).to_numpy()
columns_maxs = df.max(axis=0).to_numpy()
columns_mins

array([4.3, 2. , 1. , 0.1, 0. ])

In [5]:
train_dataset_target_model, test_dataset_target_model, train_dataset_target_model_labels, test_dataset_target_model_labels = train_test_split(data, y_true, test_size=0.2)
train = train_dataset_target_model[:,0:4]
test = test_dataset_target_model[:,0:4]

In [6]:
test_dataset_target_model

array([['5.6', '2.7', '4.2', '1.3', 'Gerard 95'],
       ['6.5', '3.0', '5.2', '2.0', 'Gerard 148'],
       ['6.7', '3.1', '5.6', '2.4', 'Gerard 141'],
       ['5.4', '3.4', '1.5', '0.4', 'Gerard 32'],
       ['7.2', '3.6', '6.1', '2.5', 'Gerard 110'],
       ['6.7', '3.0', '5.2', '2.3', 'Gerard 146'],
       ['6.8', '2.8', '4.8', '1.4', 'Gerard 77'],
       ['6.0', '2.2', '4.0', '1.0', 'Gerard 63'],
       ['7.7', '3.0', '6.1', '2.3', 'Gerard 136'],
       ['6.1', '3.0', '4.9', '1.8', 'Gerard 128'],
       ['4.9', '3.0', '1.4', '0.2', 'Gerard 2'],
       ['5.6', '3.0', '4.1', '1.3', 'Gerard 89'],
       ['5.9', '3.0', '4.2', '1.5', 'Gerard 62'],
       ['5.1', '3.3', '1.7', '0.5', 'Gerard 24'],
       ['5.0', '2.0', '3.5', '1.0', 'Gerard 61'],
       ['7.7', '2.8', '6.7', '2.0', 'Gerard 123'],
       ['6.7', '2.5', '5.8', '1.8', 'Gerard 109'],
       ['5.6', '2.9', '3.6', '1.3', 'Gerard 65'],
       ['5.6', '2.5', '3.9', '1.1', 'Gerard 70'],
       ['4.4', '3.0', '1.3', '0.2', 'Gerard

In [7]:
target_model = MLPClassifier(hidden_layer_sizes=(20,10), max_iter=1000, verbose=True).fit(train, train_dataset_target_model_labels)
target_model.score(test, test_dataset_target_model_labels)

Iteration 1, loss = 2.20710219
Iteration 2, loss = 2.16118318
Iteration 3, loss = 2.11814430
Iteration 4, loss = 2.07679312
Iteration 5, loss = 2.03675107
Iteration 6, loss = 1.99819669
Iteration 7, loss = 1.96112857
Iteration 8, loss = 1.92696352
Iteration 9, loss = 1.89417594
Iteration 10, loss = 1.86244077
Iteration 11, loss = 1.83160983
Iteration 12, loss = 1.80182057
Iteration 13, loss = 1.77290624
Iteration 14, loss = 1.74498113
Iteration 15, loss = 1.71802881
Iteration 16, loss = 1.69199831
Iteration 17, loss = 1.66682644
Iteration 18, loss = 1.64251543
Iteration 19, loss = 1.61905393
Iteration 20, loss = 1.59642593
Iteration 21, loss = 1.57470738
Iteration 22, loss = 1.55373030
Iteration 23, loss = 1.53370703
Iteration 24, loss = 1.51448872
Iteration 25, loss = 1.49628305
Iteration 26, loss = 1.47900578
Iteration 27, loss = 1.46273158
Iteration 28, loss = 1.44771298
Iteration 29, loss = 1.43385781
Iteration 30, loss = 1.42126544
Iteration 31, loss = 1.41021017
Iteration 32, los

/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


0.9333333333333333

In [8]:
target_model.predict_proba([['5.1', '3.5', '1.4', '0.2']])

/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([[9.99959895e-01, 4.00958878e-05, 9.11335902e-09]])

In [9]:
def generate_synthetic_data(k_max, c, target_model,columns_mins,columns_maxs, iterations=100, conf_min=0.99, rej_max=1000, k_min = 1):
    j = 0
    x = np.array([np.random.uniform(columns_mins[l], columns_maxs[l]) for l in range(k_max)])
    y_c = 0
    k = k_max
    for i in range(iterations):
        y_class = target_model.predict_proba([x])
        if y_class[0][c] > y_c:
            if y_class[0][c] > conf_min and c == np.argmax(y_class[0]):
                if np.random.uniform(0, 1) <= y_class[0][c]:
                   return x
            x_temp = x
            y_c = y_class[0][c]
            j = 0
        else:
            j += 1
            if j>=rej_max:
                k = max(k_min, k//2)
                j = 0
        indice = np.random.randint(0, 4, size=(1, k))
        for i in indice:
            x[i] = np.random.uniform(columns_mins[i], columns_maxs[i])
    return None

In [10]:
def generate_shadows_datasets(k_max, c_s, target_model, columns_mins, columns_maxs, mutliple_of_cs, iterations=100, conf_min=0.99, rej_max=1000, k_min = 1, n=10000):
    shadow_datasets = []
    for c in c_s:
        shadow_dataset_c = []
        print(f'Generating {c} label shadow...')
        for j in range(mutliple_of_cs):
            for i in tqdm(range(n)):
                x_k = generate_synthetic_data(k_max, c, target_model, columns_mins, columns_maxs, iterations, conf_min, rej_max, k_min)
                while x_k is None:
                    x_k = generate_synthetic_data(k_max, c, target_model, columns_mins, columns_maxs, iterations, conf_min, rej_max, k_min)
                shadow_dataset_c.append(x_k)
        print(f'{c} label shadow dataset generated\n')
        shadow_datasets.append(shadow_dataset_c)
    return shadow_datasets

In [11]:
c_s = [0, 1, 2]
mutliple_of_cs = 3
n = 10000

In [12]:
shadow_datasets = generate_shadows_datasets(4, c_s, target_model, columns_mins, columns_maxs, mutliple_of_cs=mutliple_of_cs, n=n)

Generating 0 label shadow...


100%|██████████| 10000/10000 [00:04<00:00, 2459.04it/s]


0 label shadow dataset generated

Generating 1 label shadow...


100%|██████████| 10000/10000 [00:04<00:00, 2131.86it/s]


1 label shadow dataset generated

Generating 2 label shadow...


100%|██████████| 10000/10000 [00:06<00:00, 1594.04it/s]

2 label shadow dataset generated



In [13]:
shadow_datasets_train_class_k = []
shadow_datasets_test_class_k = []
shadow_train_labels_class_k = []
shadow_test_labels_class_k = []
for k in c_s:
    temp_train_class_k, temp_test_class_k, temp_train_labels_class_k, temp_test_labels_class_k = train_test_split(shadow_datasets[k], np.full(len(shadow_datasets[k]),c_s[k]), test_size=0.5, shuffle=True)
    shadow_datasets_train_class_k.append(temp_train_class_k)
    shadow_datasets_test_class_k.append(temp_test_class_k)
    shadow_train_labels_class_k.append(temp_train_labels_class_k)
    shadow_test_labels_class_k.append(temp_test_labels_class_k)
shadow_datasets_train_class_k = np.array(shadow_datasets_train_class_k)
shadow_datasets_test_class_k = np.array(shadow_datasets_test_class_k)
shadow_train_labels_class_k = np.array(shadow_train_labels_class_k)
shadow_test_labels_class_k = np.array(shadow_test_labels_class_k)

shadow_test_labels_class_k[1]

array([1, 1, 1, ..., 1, 1, 1])

In [14]:
shadow_dataset_train_k = []
shadow_dataset_test_k = []
shadow_train_labels_k= []
shadow_test_labels_k= []
range_indices_train = len(shadow_datasets_train_class_k[0])//mutliple_of_cs
range_indices_test = len(shadow_datasets_test_class_k[0])//mutliple_of_cs
for k in range(mutliple_of_cs):
    shadow_dataset_train_k.append(np.concatenate([shadow_datasets_train_class_k[i][k*range_indices_train:(k+1)*range_indices_train] for i in range(len(c_s))]))
    shadow_dataset_test_k.append(np.concatenate([shadow_datasets_test_class_k[i][k*range_indices_test:(k+1)*range_indices_test] for i in range(len(c_s))]))
    shadow_train_labels_k.append(np.concatenate([shadow_train_labels_class_k[i][k*range_indices_train:(k+1)*range_indices_train] for i in range(len(c_s))]))
    shadow_test_labels_k.append(np.concatenate([shadow_test_labels_class_k[i][k*range_indices_test:(k+1)*range_indices_test] for i in range(len(c_s))]))
    shadow_dataset_train_k[k], shadow_train_labels_k[k] = shuffle(shadow_dataset_train_k[k], shadow_train_labels_k[k])

shadow_train_labels_k

[array([0, 1, 0, ..., 0, 1, 2]),
 array([1, 2, 0, ..., 0, 1, 0]),
 array([0, 0, 1, ..., 2, 0, 1])]

In [15]:
shadow_models = []
for k in range(mutliple_of_cs):
    print(f'Shadow model {k} training...')
    shadow_model_k = MLPClassifier(hidden_layer_sizes=(20,10), max_iter=1000).fit(shadow_dataset_train_k[k], shadow_train_labels_k[k])
    print(f'Shadow model {k} accuracy: {shadow_model_k.score(shadow_dataset_test_k[k], shadow_test_labels_k[k])}\n')
    shadow_models.append(shadow_model_k)

Shadow model 0 training...
Shadow model 0 accuracy: 1.0

Shadow model 1 training...
Shadow model 1 accuracy: 1.0

Shadow model 2 training...
Shadow model 2 accuracy: 1.0



In [16]:
def attack_training_set_in(shadow_training_dataset, shadow_train_labels_k, target_shadow_model):
    attack_dataset = []
    attack_labels = []
    print(f'Generating attack dataset in...')
    for k in range(len(shadow_training_dataset)):
        y = target_shadow_model.predict_proba([shadow_training_dataset[k]])
        attack_dataset.append([y[0], shadow_train_labels_k[k]])
        attack_labels.append(1)
    return attack_dataset, attack_labels

In [17]:
def attack_training_set_out(shadow_test_dataset, shadow_test_labels_k ,target_shadow_model):
    attack_dataset = []
    attack_labels = []
    print(f'Generating attack dataset out...')
    for k in range(len(shadow_test_dataset)):
        y = target_shadow_model.predict_proba([shadow_test_dataset[k]])
        attack_dataset.append([y[0], shadow_test_labels_k[k]])
        attack_labels.append(0)
    return attack_dataset, attack_labels

In [18]:
attack_dataset = []
attack_labels = []
for k in range(mutliple_of_cs):
    attack_dataset_in, attack_labels_in = attack_training_set_in(shadow_dataset_train_k[k], shadow_train_labels_k[k], shadow_models[k])
    attack_dataset_out, attack_labels_out = attack_training_set_out(shadow_dataset_test_k[k], shadow_test_labels_k[k], shadow_models[k])
    attack_dataset += attack_dataset_in
    attack_dataset += attack_dataset_out
    attack_labels += attack_labels_in
    attack_labels += attack_labels_out
attack_labels = np.array(attack_labels)
df = pd.DataFrame(data=attack_dataset, columns=['y', 'class'])
print(len(attack_labels))

Generating attack dataset in...
Generating attack dataset out...
Generating attack dataset in...
Generating attack dataset out...
Generating attack dataset in...
Generating attack dataset out...
90000


In [19]:
attack_dataset = []
attack_models = []
for c in c_s:
    dataset = df[df['class'] == c]['y']
    labels = attack_labels[df['class'] == c]
    dataset = np.array([x for x in dataset])
    train_dataset, test_dataset, train_labels, test_labels = train_test_split(dataset, labels, test_size=0.1, shuffle=True)
    print(sum(train_labels == 1))
    print(f'Attack model {c} training...')
    # attack_model = MLPClassifier(hidden_layer_sizes=(80, 80, 80, 80,40, 40, 40), max_iter=1000).fit(train_dataset, train_labels)
    attack_model = RandomForestClassifier(n_estimators=1000).fit(train_dataset, train_labels)
    y_pred = attack_model.predict(test_dataset)
    print(f'Attack model {c} accuracy: {attack_model.score(test_dataset, test_labels)}')
    print(f'Attack model {c} recall: {recall_score(test_labels, y_pred)}')
    print(f'Attack model {c} precision: {precision_score(test_labels, y_pred)}')
    print(f'Attack model {c} f1: {f1_score(test_labels, y_pred)}\n')
    attack_models.append(attack_model)

13494
Attack model 0 training...
Attack model 0 accuracy: 0.49466666666666664
Attack model 0 recall: 0.897742363877822
Attack model 0 precision: 0.49815770081061167
Attack model 0 f1: 0.6407582938388626

13465
Attack model 1 training...
Attack model 1 accuracy: 0.491
Attack model 1 recall: 0.24560260586319219
Attack model 1 precision: 0.5053619302949062
Attack model 1 f1: 0.3305567733450241

13486
Attack model 2 training...
Attack model 2 accuracy: 0.503
Attack model 2 recall: 0.42668428005284015
Attack model 2 precision: 0.5090622537431048
Attack model 2 f1: 0.46424721523535745



In [20]:
In_samples_y_0 = target_model.predict_proba(train[np.where(train_dataset_target_model_labels == 0)])
In_samples_y_1 = target_model.predict_proba(train[np.where(train_dataset_target_model_labels == 1)])
In_samples_y_2 = target_model.predict_proba(train[np.where(train_dataset_target_model_labels == 2)])

Out_samples_y_0 = target_model.predict_proba(test[np.where(test_dataset_target_model_labels == 0)])
Out_samples_y_1 = target_model.predict_proba(test[np.where(test_dataset_target_model_labels == 1)])
Out_samples_y_2 = target_model.predict_proba(test[np.where(test_dataset_target_model_labels == 2)])

labels_in_0 = np.full(len(In_samples_y_0), 1)
labels_in_1 = np.full(len(In_samples_y_1), 1)
labels_in_2 = np.full(len(In_samples_y_2), 1)

labels_out_0 = np.full(len(Out_samples_y_0), 0)
labels_out_1 = np.full(len(Out_samples_y_1), 0)
labels_out_2 = np.full(len(Out_samples_y_2), 0)

evaluation_0 = np.concatenate((In_samples_y_0, Out_samples_y_0))
evaluation_1 = np.concatenate((In_samples_y_1, Out_samples_y_1))
evaluation_2 = np.concatenate((In_samples_y_2, Out_samples_y_2))

labels_0 = np.concatenate((labels_in_0, labels_out_0))
labels_1 = np.concatenate((labels_in_1, labels_out_1))
labels_2 = np.concatenate((labels_in_2, labels_out_2))

y_pred_0 = attack_models[0].predict(evaluation_0)
y_pred_1 = attack_models[1].predict(evaluation_1)
y_pred_2 = attack_models[2].predict(evaluation_2)

print(f'Attack model accuracy on class 0: {accuracy_score(labels_0, y_pred_0)}')
print(f'Attack model recall on class 0: {recall_score(labels_0, y_pred_0)}')
print(f'Attack model precision on class 0: {precision_score(labels_0, y_pred_0)}')
print(f'Attack model f1 on class 0: {f1_score(labels_0, y_pred_0)}\n')

print(f'Attack model accuracy on class 1: {accuracy_score(labels_1, y_pred_1)}')
print(f'Attack model recall on class 1: {recall_score(labels_1, y_pred_1)}')
print(f'Attack model precision on class 1: {precision_score(labels_1, y_pred_1)}')
print(f'Attack model f1 on class 1: {f1_score(labels_1, y_pred_1)}\n')

print(f'Attack model accuracy on class 2: {accuracy_score(labels_2, y_pred_2)}')
print(f'Attack model recall on class 2: {recall_score(labels_2, y_pred_2)}')
print(f'Attack model precision on class 2: {precision_score(labels_2, y_pred_2)}')
print(f'Attack model f1 on class 2: {f1_score(labels_2, y_pred_2)}\n')

Attack model accuracy on class 0: 0.46
Attack model recall on class 0: 0.4772727272727273
Attack model precision on class 0: 0.84
Attack model f1 on class 0: 0.6086956521739131

Attack model accuracy on class 1: 0.76
Attack model recall on class 1: 0.9743589743589743
Attack model precision on class 1: 0.7755102040816326
Attack model f1 on class 1: 0.8636363636363635

Attack model accuracy on class 2: 0.6
Attack model recall on class 2: 0.6756756756756757
Attack model precision on class 2: 0.7575757575757576
Attack model f1 on class 2: 0.7142857142857142



/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)
/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)
/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to nume

In [21]:
new_target_model = MLPClassifier(hidden_layer_sizes=(20,10), max_iter=50, verbose=True).fit(train, train_dataset_target_model_labels)
new_target_model.score(test, test_dataset_target_model_labels)

Iteration 1, loss = 1.06395077
Iteration 2, loss = 1.04768828
Iteration 3, loss = 1.03208214
Iteration 4, loss = 1.01705012
Iteration 5, loss = 1.00262801
Iteration 6, loss = 0.98879970
Iteration 7, loss = 0.97555023
Iteration 8, loss = 0.96294728
Iteration 9, loss = 0.95094137
Iteration 10, loss = 0.93955790
Iteration 11, loss = 0.92883403
Iteration 12, loss = 0.91880556
Iteration 13, loss = 0.90933820
Iteration 14, loss = 0.90038612
Iteration 15, loss = 0.89189427
Iteration 16, loss = 0.88384151
Iteration 17, loss = 0.87619368
Iteration 18, loss = 0.86884724
Iteration 19, loss = 0.86190531
Iteration 20, loss = 0.85537074
Iteration 21, loss = 0.84924177
Iteration 22, loss = 0.84321762
Iteration 23, loss = 0.83724032
Iteration 24, loss = 0.83123750
Iteration 25, loss = 0.82518365
Iteration 26, loss = 0.81907322
Iteration 27, loss = 0.81293177
Iteration 28, loss = 0.80680560
Iteration 29, loss = 0.80066230
Iteration 30, loss = 0.79451207
Iteration 31, loss = 0.78844731
Iteration 32, los

/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


0.5666666666666667

In [22]:
In_samples_y_0 = new_target_model.predict_proba(train[np.where(train_dataset_target_model_labels == 0)])
In_samples_y_1 = new_target_model.predict_proba(train[np.where(train_dataset_target_model_labels == 1)])
In_samples_y_2 = new_target_model.predict_proba(train[np.where(train_dataset_target_model_labels == 2)])

Out_samples_y_0 = new_target_model.predict_proba(test[np.where(test_dataset_target_model_labels == 0)])
Out_samples_y_1 = new_target_model.predict_proba(test[np.where(test_dataset_target_model_labels == 1)])
Out_samples_y_2 = new_target_model.predict_proba(test[np.where(test_dataset_target_model_labels == 2)])

labels_in_0 = np.full(len(In_samples_y_0), 1)
labels_in_1 = np.full(len(In_samples_y_1), 1)
labels_in_2 = np.full(len(In_samples_y_2), 1)

labels_out_0 = np.full(len(Out_samples_y_0), 0)
labels_out_1 = np.full(len(Out_samples_y_1), 0)
labels_out_2 = np.full(len(Out_samples_y_2), 0)

evaluation_0 = np.concatenate((In_samples_y_0, Out_samples_y_0))
evaluation_1 = np.concatenate((In_samples_y_1, Out_samples_y_1))
evaluation_2 = np.concatenate((In_samples_y_2, Out_samples_y_2))

labels_0 = np.concatenate((labels_in_0, labels_out_0))
labels_1 = np.concatenate((labels_in_1, labels_out_1))
labels_2 = np.concatenate((labels_in_2, labels_out_2))

y_pred_0 = attack_models[0].predict(evaluation_0)
y_pred_1 = attack_models[1].predict(evaluation_1)
y_pred_2 = attack_models[2].predict(evaluation_2)

print(f'Attack model accuracy on class 0: {accuracy_score(labels_0, y_pred_0)}')
print(f'Attack model recall on class 0: {recall_score(labels_0, y_pred_0)}')
print(f'Attack model precision on class 0: {precision_score(labels_0, y_pred_0)}')
print(f'Attack model f1 on class 0: {f1_score(labels_0, y_pred_0)}\n')

print(f'Attack model accuracy on class 1: {accuracy_score(labels_1, y_pred_1)}')
print(f'Attack model recall on class 1: {recall_score(labels_1, y_pred_1)}')
print(f'Attack model precision on class 1: {precision_score(labels_1, y_pred_1)}')
print(f'Attack model f1 on class 1: {f1_score(labels_1, y_pred_1)}\n')

print(f'Attack model accuracy on class 2: {accuracy_score(labels_2, y_pred_2)}')
print(f'Attack model recall on class 2: {recall_score(labels_2, y_pred_2)}')
print(f'Attack model precision on class 2: {precision_score(labels_2, y_pred_2)}')
print(f'Attack model f1 on class 2: {f1_score(labels_2, y_pred_2)}\n')

/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)
/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)
/Users/jskaf/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to nume

Attack model accuracy on class 0: 0.88
Attack model recall on class 0: 1.0
Attack model precision on class 0: 0.88
Attack model f1 on class 0: 0.9361702127659575

Attack model accuracy on class 1: 0.78
Attack model recall on class 1: 1.0
Attack model precision on class 1: 0.78
Attack model f1 on class 1: 0.8764044943820225

Attack model accuracy on class 2: 0.74
Attack model recall on class 2: 1.0
Attack model precision on class 2: 0.74
Attack model f1 on class 2: 0.8505747126436781

